name: "Build Container Image"
on: [push, pull_request]

defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docker:
    name: "Build Container image"
    runs-on: ubuntu-latest
    env:
      CONTAINER_IMAGE_NAME: http://localhost:5000/yami:${{ github.sha }}

    steps:
      - name: Checkout the branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

	  - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true
          version: latest

      - name: Login to OpenRegistry
        uses: docker/login-action@v3
        with:
          registry: http://localhost:5000
          username: yami
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          target: runner
          tags: ${{ env.CONTAINER_IMAGE_NAME }}
